import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        note: {
          default: "hsl(var(--note-default))",
          "default-border": "hsl(var(--note-default-border))",
          rose: "hsl(var(--note-rose))",
          "rose-border": "hsl(var(--note-rose-border))",
          red: "hsl(var(--note-red))",
          "red-border": "hsl(var(--note-red-border))",
          pink: "hsl(var(--note-pink))",
          "pink-border": "hsl(var(--note-pink-border))",
          fuchsia: "hsl(var(--note-fuchsia))",
          "fuchsia-border": "hsl(var(--note-fuchsia-border))",
          violet: "hsl(var(--note-violet))",
          "violet-border": "hsl(var(--note-violet-border))",
          purple: "hsl(var(--note-purple))",
          "purple-border": "hsl(var(--note-purple-border))",
          indigo: "hsl(var(--note-indigo))",
          "indigo-border": "hsl(var(--note-indigo-border))",
          navy: "hsl(var(--note-navy))",
          "navy-border": "hsl(var(--note-navy-border))",
          blue: "hsl(var(--note-blue))",
          "blue-border": "hsl(var(--note-blue-border))",
          sky: "hsl(var(--note-sky))",
          "sky-border": "hsl(var(--note-sky-border))",
          cyan: "hsl(var(--note-cyan))",
          "cyan-border": "hsl(var(--note-cyan-border))",
          teal: "hsl(var(--note-teal))",
          "teal-border": "hsl(var(--note-teal-border))",
          mint: "hsl(var(--note-mint))",
          "mint-border": "hsl(var(--note-mint-border))",
          emerald: "hsl(var(--note-emerald))",
          "emerald-border": "hsl(var(--note-emerald-border))",
          green: "hsl(var(--note-green))",
          "green-border": "hsl(var(--note-green-border))",
          lime: "hsl(var(--note-lime))",
          "lime-border": "hsl(var(--note-lime-border))",
          yellow: "hsl(var(--note-yellow))",
          "yellow-border": "hsl(var(--note-yellow-border))",
          amber: "hsl(var(--note-amber))",
          "amber-border": "hsl(var(--note-amber-border))",
          gold: "hsl(var(--note-gold))",
          "gold-border": "hsl(var(--note-gold-border))",
          orange: "hsl(var(--note-orange))",
          "orange-border": "hsl(var(--note-orange-border))",
          maroon: "hsl(var(--note-maroon))",
          "maroon-border": "hsl(var(--note-maroon-border))",
          coffee: "hsl(var(--note-coffee))",
          "coffee-border": "hsl(var(--note-coffee-border))",
          slate: "hsl(var(--note-slate))",
          "slate-border": "hsl(var(--note-slate-border))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        elegant: "0 1px 2px hsl(var(--shadow-color) / 0.04), 0 4px 8px hsl(var(--shadow-color) / 0.04), 0 8px 16px hsl(var(--shadow-color) / 0.04)",
        elevated: "0 2px 4px hsl(var(--shadow-color) / 0.06), 0 8px 16px hsl(var(--shadow-color) / 0.08), 0 16px 32px hsl(var(--shadow-color) / 0.08)",
        glow: "0 0 24px hsl(var(--glow-primary) / 0.2)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(4px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in": {
          from: { opacity: "0", transform: "translateX(-8px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "pulse-subtle": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.7" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.2s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        "pulse-subtle": "pulse-subtle 2s ease-in-out infinite",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
